const axios = require('axios');

module.exports = {
    command: ['animes', 'anime'],
    category: 'fun',
    execute: async (sock, m, { reply }) => { // <--- Hakikisha kuna mabano ya { }
        try {
            await sock.sendMessage(m.chat, { react: { text: "⛩️", key: m.key } });
            
            const res = await axios.get('https://api.waifu.pics/sfw/waifu');
            await sock.sendMessage(m.chat, { 
                image: { url: res.data.url }, 
                caption: `🏮 *ANIME GENERATED BY DARKX*` 
            }, { quoted: m });

        } catch (e) {
            console.error(e);
            if (reply) reply("❌ Imeshindwa kupata picha ya anime.");
        }
    }
};
